name: clean_reproducible_code
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.10.6
  - readline=8.1.2
  - setuptools=65.5.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - accessible-pygments==0.0.5
    - alabaster==0.7.16
    - anyio==4.12.1
    - appnope==0.1.4
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.1
    - attrs==25.4.0
    - autopep8==2.3.2
    - babel==2.17.0
    - beautifulsoup4==4.14.3
    - black==26.1.0
    - bleach==6.3.0
    - certifi==2026.1.4
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - debugpy==1.8.19
    - decorator==5.2.1
    - defusedxml==0.7.1
    - docutils==0.20.1
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.20.3
    - flake8==7.3.0
    - fonttools==4.61.1
    - fqdn==1.5.1
    - fsspec==2026.1.0
    - greenlet==3.3.0
    - idna==3.11
    - imagesize==1.4.1
    - importlib-metadata==8.7.1
    - iniconfig==2.3.0
    - ipykernel==7.1.0
    - ipython==8.38.0
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.3
    - jsonpointer==3.0.0
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - jupyter-book==1.0.3
    - jupyter-cache==1.0.1
    - jupyter-client==8.8.0
    - jupyter-core==5.9.1
    - jupyter-events==0.12.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.4
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.9
    - lark==1.3.1
    - latexcodec==3.0.1
    - linkify-it-py==2.0.3
    - markdown-it-py==3.0.0
    - markupsafe==3.0.3
    - matplotlib==3.8.2
    - matplotlib-inline==0.2.1
    - mccabe==0.7.0
    - mdit-py-plugins==0.5.0
    - mdurl==0.1.2
    - mistune==3.2.0
    - mpmath==1.3.0
    - mypy-extensions==1.1.0
    - myst-nb==1.3.0
    - myst-parser==2.0.0
    - nbclient==0.10.4
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nodeenv==1.10.0
    - numpy==1.26.4
    - overrides==7.7.0
    - packaging==25.0
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pathspec==1.0.3
    - pexpect==4.9.0
    - pillow==12.1.0
    - platformdirs==4.5.1
    - pluggy==1.6.0
    - prometheus-client==0.24.1
    - prompt-toolkit==3.0.52
    - psutil==7.2.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pybtex==0.25.1
    - pybtex-docutils==1.0.3
    - pycodestyle==2.14.0
    - pycparser==2.23
    - pydata-sphinx-theme==0.15.4
    - pyflakes==3.4.0
    - pygments==2.19.2
    - pyparsing==3.3.1
    - pytest==9.0.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pytokens==0.3.0
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.37.0
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.30.0
    - scikit-learn==1.4.0
    - scipy==1.15.3
    - seaborn==0.11.0
    - send2trash==2.1.0
    - six==1.17.0
    - snowballstemmer==3.0.1
    - soupsieve==2.8.2
    - sphinx==7.4.7
    - sphinx-book-theme==1.1.4
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.2
    - sphinx-design==0.6.1
    - sphinx-external-toc==1.1.0
    - sphinx-jupyterbook-latex==1.0.0
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.3.1
    - sphinx-togglebutton==0.4.4
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-bibtex==2.6.5
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sqlalchemy==2.0.45
    - stack-data==0.6.3
    - sympy==1.14.0
    - tabulate==0.9.0
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tinycss2==1.4.0
    - tomli==2.4.0
    - torch==2.2.2
    - tornado==6.5.4
    - traitlets==5.14.3
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - uc-micro-py==1.0.3
    - uri-template==1.3.0
    - urllib3==2.6.3
    - wcwidth==0.2.14
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - zipp==3.23.0
